OutputDir=/Volumes/develop/xuebay/xuebay-service/xuebay-cart-service/src/main/java

OutputDirXml=/Volumes/develop/xuebay/xuebay-service/xuebay-cart-service/src/main/resources

OutputDirBase=/Volumes/develop/xuebay/xuebay-model/xuebay-cart-model/src/main/java

author=${author}

parent=${package-name}

jdbc.driver=com.mysql.jdbc.Driver

jdbc.url=jdbc:mysql://${your-mysql-server-host}:${your-mysql-server-port}/xuebay-system?serverTimezone=UTC

jdbc.user=${your-mysql-server-username}

jdbc.pwd=${your-mysql-server-password}